from selenium import webdriver
from time import sleep
import datetime

driver = webdriver.Chrome()
url = 'http://warehouse.test.com/index.html'
driver.get(url)
driver.maximize_window()
de

driver.find_element_by_xpath("//input[@type='text']").click()
driver.find_element_by_xpath("//input[@type='text']").clear()
driver.find_element_by_xpath("//input[@type='text']").send_keys("abc")


driver.find_element_by_xpath("//input[@type='password']").click()
driver.find_element_by_xpath("//input[@type='password']").clear()
driver.find_element_by_xpath("//input[@type='password']").send_keys("abc")

driver.find_element_by_xpath("(//button[@type='button'])[2]").click()
sleep(1)



driver.find_element_by_xpath("//li[3]/div").click()
sleep(1)
driver.find_element_by_xpath("//li/li[3]/ul/li/a").click()
sleep(1)
driver.find_element_by_xpath("//div/button[3][@type='button']").click()
driver.find_element_by_xpath("//div/div[2]/input[@placeholder='请输入供应商名称']").click()
driver.find_element_by_xpath("//div/div[2]/input[@placeholder='请输入供应商名称']").send_keys("默认采购商")
sleep(1)
driver.find_element_by_xpath("//div/div[2]/ul/li/a").click()
sleep(1)
driver.find_element_by_xpath("//button[@type='button']").click()
sleep(1)
driver.find_element_by_xpath("//td/input[@placeholder='请输入物料名称']").click()
driver.find_element_by_xpath("//td/input[@placeholder='请输入物料名称']").send_keys("i")
sleep(1)
driver.find_element_by_xpath("//td/input[@placeholder='请输入物料名称']").send_keys("p")
sleep(1)
driver.find_element_by_xpath("//div/ul/li[6]/a").click()
driver.find_element_by_xpath("//table/tbody/tr/td[4]/input[@type='text']").click()
driver.find_element_by_xpath("//table/tbody/tr/td[4]/input[@type='text']").send_keys("2")
sleep(1)
driver.find_element_by_xpath("//html/body/div/div[2]/main/div/div/form/div[2]/div/table/tbody/tr[1]/td[5]/input[@type='text']").click()
driver.find_element_by_xpath("//html/body/div/div[2]/main/div/div/form/div[2]/div/table/tbody/tr[1]/td[5]/input[@type='text']").send_keys("999")
sleep(1)
driver.find_element_by_xpath("//button[@type='submit']").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[2]/div/div/div[3]/a[2]").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/div[1]/nav/ul/li/li[3]/ul[2]/li/a").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[1]/div/table/tbody/tr[1]/td[9]/a").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[2]/div/div/div[3]/a[1]").click()
sleep(1)
# driver.find_element_by_xpath("/html/body/div/div[2]/div[1]/nav/ul/li/li[3]/ul[3]/li/a").click()
sleep(1)
# driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[1]/div/table/tbody/tr[1]/td[11]/a[1]").click()
sleep(1)
# driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[8]/a").click()
sleep(1)
# driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[3]/div/div/div[2]/table/tbody/tr[1]/td/input").click()

driver.find_element_by_xpath("/html/body/div/div[2]/div[1]/nav/ul/li/li[3]/ul[3]/li/a").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[1]/div/table/tbody/tr[1]/td[11]/a[1]").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[8]/a").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[3]/div/div/div[2]/table/tbody/tr[1]/td/input").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[3]/div/div/div[2]/table/tbody/tr[1]/td/input").send_keys('{0:%Y%m%d%H%M%S}'.format ( datetime.datetime.now () ))
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[3]/div/div/div[2]/table/tbody/tr[2]/td/input").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[3]/div/div/div[2]/table/tbody/tr[2]/td/input").send_keys('{0:%Y%m%d%H%M%S}'.format ( datetime.datetime.now () ))
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[3]/div/div/div[3]/a[1]").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/main/div/div/div[2]/div/div/div[3]/a[1]").click()
sleep(1)
driver.find_element_by_xpath(u"(//a[contains(text(),'取消')])[5]").click()
sleep(4)
driver.close()


# driver.close()
